<a href="https://colab.research.google.com/github/salvatorxx/Exam/blob/main/sess1_mentor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
print("nilai" + str(10))

nilai10


In [7]:
print ("nilai %d adalah integer" % 45)

nilai 45 adalah integer


In [10]:
print("nilai float : %.4f" % 32.012)

nilai float : 32.0120


In [11]:
print("nilai %d + %d sama dengan %d" % (10, 2, (10+2)))

nilai 10 + 2 sama dengan 12


PENAMAAN VARIABEL

In [ ]:
# bisanya pake _

In [16]:
1variabel = 10

SyntaxError: ignored

In [17]:
$variabel = "hello world"

SyntaxError: ignored

In [18]:
-var = 10

SyntaxError: ignored

In [22]:
_var = 10
__var = 10
_______________var = 10
_var_ = 10

In [23]:
_umur = 20
type (_umur)

int

int() untuk mengubah menjadi integer;
long() untuk mengubah menjadi integer panjang;
float() untuk mengubah menjadi float;
bool() untuk mengubah menjadi boolean;
chr() untuk mengubah menjadi karakter;
str() untuk mengubah menjadi string.
bin() untuk mengubah menjadi bilangan Biner.
hex() untuk mengubah menjadi bilangan Heksadesimal.
oct() untuk mengubah menjadi bilangan okta.

INPUT

In [24]:
A = input("var A : ")
B = input("var B : ")

C = int(A) + int(B)
print("A + B = " + str(C))

var A : 4
var B : 5
A + B = 9


In [27]:
D = input("var D : ")
E = input("var E : ")

str(C) = str(D) + str(E)
print("A + B = " + str(C))

SyntaxError: ignored

NUMPY

In [ ]:
 # numpy -> numerical python

In [ ]:
#array -> n dimensional array

#n = 0,1,2,3
#n = 0 -> 0 dimensional array 

In [29]:
#0-d
x = np.array(2, dtype=int)
print(x)

2


In [32]:
#1-d (vektor)
arr = [1,2,3]
x = np.array(arr, dtype=int)
print(x)

y = np.array([1,2,3,4,5,6])
print(y)

[1 2 3]
[1 2 3 4 5 6]


In [34]:
#2-d (matrix)
matrix = np.array([[1,2,3,5],
                   [4,5,6,6],
                   [7,8,9,9]])
print(matrix)
matrix.shape

[[1 2 3 5]
 [4 5 6 6]
 [7 8 9 9]]


(3, 4)

In [ ]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10,11,12]]])

CREATE MATRIX ZERO

In [36]:
a = np.ones(100)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


In [38]:
zero_matrix = np.zeros((2,3,2))
print(zero_matrix)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


GENERATE MATRIX

In [ ]:
#random -> np.linspace()

In [40]:
generated_matrix = np.linspace(1,5)
print(generated_matrix)

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [41]:
generated_matrix = np.linspace(1,5,10)
print(generated_matrix)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [42]:
generated_matrix = np.linspace(0,5,6)
print(generated_matrix)

[0. 1. 2. 3. 4. 5.]


AKSES ELEMEN VEKTOR

In [43]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [46]:
matrix[-1] #akses abris index -1 (baris paling akhir)

array([7, 8, 9, 9])

In [51]:
#akses pake slice
matrix[1:]

array([[4, 5, 6, 6],
       [7, 8, 9, 9]])

In [56]:
matrix[0:2]

array([[1, 2, 3, 5],
       [4, 5, 6, 6]])

In [58]:
#akses kolom dalam matrix 2d
myList = [[1,2,3], 
          [4,5,6]]
myList[0]

[1, 2, 3]

In [60]:
myList[1][2] #myList [baris][kolom] index -> 0,1,2

6

In [61]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [ ]:
#idx  [0, 1, 2, 3]

In [66]:
matrix[:,1] # matrix -> [baris, kolom] (: -> baris , -1 -> kolom)

array([2, 5, 8])

In [70]:
matrix[:, 2:3]

array([[3],
       [6],
       [9]])

In [72]:
matrix

array([[1, 2, 3, 5],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [75]:
matrix[0, 0:3 ] #matrix = angka dari index 0 sampai index <3

array([1, 2, 3])

In [76]:
#ambil [123, 456]
matrix[0:2, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

akses 3 dimensi

In [77]:
matrix = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10,11,12]]])

In [79]:
matrix.shape

(2, 2, 3)

In [80]:
matrix[1]

array([[ 7,  8,  9],
       [10, 11, 12]])